name: Dwaya
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.7.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^0.1.3
    provider: ^4.3.2
    shared_preferences: ^0.4.2
    http: ^0.12.0+4
    dropdown_formfield: ^0.1.2
    datetime_picker_formfield: ^1.0.0
    worm_indicator: 0.2.4
    smooth_page_indicator: ^0.2.0
    dots_indicator: ^1.2.0
    get: ^3.0.1
    flappy_search_bar: 1.4.1
    bottom_navy_bar: ^3.0.0
    implicitly_animated_reorderable_list: ^0.1.5
    flutter_slidable:
    folding_cell: ^1.0.0
    flutter_rating_bar: ^3.0.1+1
    logger: ^0.9.2
    random_color: ^1.0.5
    flutter_barcode_scanner: ^1.0.1
    webview_flutter: ^0.3.22+1
    web_socket_channel: ^1.1.0
    firebase_core: 0.5.0
    cloud_firestore: ^0.14.0+2
    geolocator: ^5.3.1
    animated_dialog_box: ^0.0.2
    flutter_local_notifications: ^1.4.4+1
    image_picker: ^0.6.7+12
    cached_network_image: ^2.2.0
    flutter_cache_manager: ^1.3.0
    tesseract_ocr: ^0.3.0
    modal_progress_hud: ^0.1.3
    firebase_messaging: ^6.0.12
    stream_chat_flutter: ^0.1.2

dev_dependencies:
    flutter_test:
        sdk: flutter
flutter:
    uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
    assets:
            - assets/images/logo2.png
            - assets/images/logo.png
            - assets/json/gouv.json
            - assets/images/banner.png
            - assets/images/download.jpg
            - assets/images/yaourt.jpg
            - assets/images/lait.png
            - assets/images/harissa.jpg
            - assets/images/chroba.jpg
            - assets/images/couscous.png
            - assets/images/chocolat lindt.png
            - assets/images/champignon.png
            - assets/images/cafe.jpg
            - assets/images/gazeuse.jpg
            - assets/images/medicaments.jpg
            - assets/images/medic.jpg
            - assets/images/clamoxyle.jpg
            - assets/tessdata_config.json
            - assets/tessdata/eng.traineddata
            - assets/tessdata/fra.traineddata
            - assets/tessdata/financial.traineddata
            - assets/tessdata/OCRB.traineddata
            - assets/tessdata/pdf.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages